Repository 36-APPJAM-HEARTZ/ByeBoo-SERVER, pull requests merged in 2025-07, with the labels that each got.

#12 [Feature] - 엔티티 추가
  src/main/java/com/heartz/byeboo/adapter/in/web/controller/HealthCheckController.java
  src/main/java/com/heartz/byeboo/adapter/out/persistence/entity/QuestEntity.java
  src/main/java/com/heartz/byeboo/adapter/out/persistence/entity/TipEntity.java
  src/main/java/com/heartz/byeboo/adapter/out/persistence/entity/UserEntity.java
  src/main/java/com/heartz/byeboo/adapter/out/persistence/entity/UserJourneyEntity.java
  src/main/java/com/heartz/byeboo/adapter/out/persistence/entity/UserQuestEntity.java
  src/main/java/com/heartz/byeboo/domain/model/Quest.java
  src/main/java/com/heartz/byeboo/domain/model/Tip.java
  src/main/java/com/heartz/byeboo/domain/model/User.java
  src/main/java/com/heartz/byeboo/domain/model/UserJourney.java
  src/main/java/com/heartz/byeboo/domain/model/UserQuest.java
  src/main/java/com/heartz/byeboo/domain/type/EJourney.java
  src/main/java/com/heartz/byeboo/domain/type/EJourneyStatus.java
  src/main/java/com/heartz/byeboo/domain/type/EQuestEmotionState.java
  src/main/java/com/heartz/byeboo/domain/type/EQuestStyle.java
  src/main/java/com/heartz/byeboo/domain/type/EStep.java
  src/main/java/com/heartz/byeboo/mapper/UserJourneyMapper.java
  src/main/java/com/heartz/byeboo/mapper/UserMapper.java
  src/main/java/com/heartz/byeboo/mapper/UserQuestMapper.java
Labels: ✨ Feature

#15 [Feature] - 유저 정보 저장 API 구현
  src/main/java/com/heartz/byeboo/adapter/in/web/controller/UserController.java
  src/main/java/com/heartz/byeboo/adapter/in/web/dto/UserCreateRequestDto.java
  src/main/java/com/heartz/byeboo/adapter/in/web/dto/UserCreateResponseDto.java
  src/main/java/com/heartz/byeboo/adapter/out/UserJourneyPersistenceAdapter.java
  src/main/java/com/heartz/byeboo/adapter/out/UserPersistenceAdapter.java
  src/main/java/com/heartz/byeboo/adapter/out/persistence/repository/UserJourneyRepository.java
  src/main/java/com/heartz/byeboo/adapter/out/persistence/repository/UserRepository.java
  src/main/java/com/heartz/byeboo/application/command/UserCreateCommand.java
  src/main/java/com/heartz/byeboo/application/port/in/UserUseCase.java
  src/main/java/com/heartz/byeboo/application/port/out/CreateUserJourneyPort.java
  src/main/java/com/heartz/byeboo/application/port/out/CreateUserPort.java
  src/main/java/com/heartz/byeboo/application/service/UserService.java
  src/main/java/com/heartz/byeboo/domain/exception/UserErrorCode.java
  src/main/java/com/heartz/byeboo/domain/model/User.java
  src/main/java/com/heartz/byeboo/domain/model/UserJourney.java
  src/main/java/com/heartz/byeboo/mapper/UserMapper.java
Labels: ✨ Feature, 🦊 상범 🦊

#31 [Feature] - 완료된 퀘스트 개수 조회 API 구현
  src/main/java/com/heartz/byeboo/adapter/in/web/controller/UserController.java
  src/main/java/com/heartz/byeboo/adapter/in/web/controller/UserQuestController.java
  src/main/java/com/heartz/byeboo/adapter/in/web/dto/request/ActiveQuestRequestDto.java
  src/main/java/com/heartz/byeboo/adapter/in/web/dto/request/HomeCountRequestDto.java
  src/main/java/com/heartz/byeboo/adapter/in/web/dto/request/RecordingQuestRequestDto.java
  src/main/java/com/heartz/byeboo/adapter/in/web/dto/request/UserCreateRequestDto.java
  src/main/java/com/heartz/byeboo/adapter/in/web/dto/response/HomeCountResponseDto.java
  src/main/java/com/heartz/byeboo/adapter/in/web/dto/response/UserCreateResponseDto.java
  src/main/java/com/heartz/byeboo/adapter/in/web/dto/response/UserJourneyResponseDto.java
  src/main/java/com/heartz/byeboo/adapter/in/web/dto/response/UserNameResponseDto.java
  src/main/java/com/heartz/byeboo/adapter/out/QuestPersistenceAdapter.java
  src/main/java/com/heartz/byeboo/adapter/out/UserQuestPersistenceAdapter.java
  src/main/java/com/heartz/byeboo/adapter/out/persistence/entity/QuestEntity.java
  src/main/java/com/heartz/byeboo/adapter/out/persistence/entity/TipEntity.java
  src/main/java/com/heartz/byeboo/adapter/out/persistence/repository/QuestRepository.java
  src/main/java/com/heartz/byeboo/adapter/out/persistence/repository/UserQuestRepository.java
  src/main/java/com/heartz/byeboo/application/command/ActiveQuestCreateCommand.java
  src/main/java/com/heartz/byeboo/application/command/HomeCountCommand.java
  src/main/java/com/heartz/byeboo/application/command/RecordingQuestCreateCommand.java
  src/main/java/com/heartz/byeboo/application/command/UserCreateCommand.java
  src/main/java/com/heartz/byeboo/application/port/in/UserUseCase.java
  src/main/java/com/heartz/byeboo/application/port/out/RetrieveQuestPort.java
  src/main/java/com/heartz/byeboo/application/port/out/RetrieveUserQuestPort.java
  src/main/java/com/heartz/byeboo/application/service/UserService.java
  src/main/java/com/heartz/byeboo/domain/exception/UserQuestErrorCode.java
  src/main/java/com/heartz/byeboo/domain/model/UserQuest.java
  src/main/java/com/heartz/byeboo/mapper/UserQuestMapper.java
Labels: ✨ Feature, 🦊 상범 🦊

#35 [Feature] - 작성된 퀘스트 상세 조회 API 구현
  src/main/java/com/heartz/byeboo/adapter/in/web/controller/UserQuestController.java
  src/main/java/com/heartz/byeboo/adapter/in/web/dto/response/QuestDetailResponseDto.java
  src/main/java/com/heartz/byeboo/adapter/out/GcsAdapter.java
  src/main/java/com/heartz/byeboo/adapter/out/UserQuestPersistenceAdapter.java
  src/main/java/com/heartz/byeboo/adapter/out/persistence/repository/UserQuestRepository.java
  src/main/java/com/heartz/byeboo/application/command/ActiveQuestCreateCommand.java
  src/main/java/com/heartz/byeboo/application/command/QuestDetailCommand.java
  src/main/java/com/heartz/byeboo/application/command/RecordingQuestCreateCommand.java
  src/main/java/com/heartz/byeboo/application/command/SignedUrlCreateCommand.java
  src/main/java/com/heartz/byeboo/application/port/in/QuestUseCase.java
  src/main/java/com/heartz/byeboo/application/port/out/RetrieveGcsPort.java
  src/main/java/com/heartz/byeboo/application/port/out/RetrieveQuestPort.java
  src/main/java/com/heartz/byeboo/application/port/out/RetrieveUserQuestPort.java
  src/main/java/com/heartz/byeboo/application/port/out/ValidateGcsPort.java
  src/main/java/com/heartz/byeboo/application/service/QuestService.java
  src/main/java/com/heartz/byeboo/domain/exception/UserQuestErrorCode.java
Labels: ✨ Feature, 🐥 현정 🐥

#41 [Feature] - 캐릭터 대사 조회 API 구현
  src/main/java/com/heartz/byeboo/adapter/in/web/controller/UserController.java
  src/main/java/com/heartz/byeboo/adapter/in/web/dto/response/UserCharacterResponseDto.java
  src/main/java/com/heartz/byeboo/application/command/ActiveQuestCreateCommand.java
  src/main/java/com/heartz/byeboo/application/command/RecordingQuestCreateCommand.java
  src/main/java/com/heartz/byeboo/application/command/UserCharacterDialogueCommand.java
  src/main/java/com/heartz/byeboo/application/port/in/UserUseCase.java
  src/main/java/com/heartz/byeboo/application/service/UserQuestService.java
  src/main/java/com/heartz/byeboo/application/service/UserService.java
  src/main/java/com/heartz/byeboo/constants/QuestConstants.java
  src/main/java/com/heartz/byeboo/domain/type/ECharacterDialogue.java
  src/main/java/com/heartz/byeboo/domain/type/EQuestEmotionState.java
Labels: ✨ Feature, 🦊 상범 🦊

#43 [Feature] - 완료된 퀘스트 여정 조회 API 구현
  src/main/java/com/heartz/byeboo/adapter/in/web/controller/QuestController.java
  src/main/java/com/heartz/byeboo/adapter/in/web/controller/UserQuestController.java
  src/main/java/com/heartz/byeboo/adapter/in/web/dto/response/JourneyListResponseDto.java
  src/main/java/com/heartz/byeboo/adapter/in/web/dto/response/JourneyResponseDto.java
  src/main/java/com/heartz/byeboo/adapter/in/web/dto/response/QuestDetailResponseDto.java
  src/main/java/com/heartz/byeboo/adapter/out/UserJourneyPersistenceAdapter.java
  src/main/java/com/heartz/byeboo/application/command/CompletedJourneyCommand.java
  src/main/java/com/heartz/byeboo/application/port/in/QuestUseCase.java
  src/main/java/com/heartz/byeboo/application/port/in/UserQuestUseCase.java
  src/main/java/com/heartz/byeboo/application/port/out/RetrieveUserJourneyPort.java
  src/main/java/com/heartz/byeboo/application/service/UserQuestService.java
  src/main/java/com/heartz/byeboo/domain/type/EJourney.java
  src/main/java/com/heartz/byeboo/mapper/JourneyStyleMapper.java
Labels: ✨ Feature, 🐥 현정 🐥

#45 [Feature] - 새로운 여정 시작하기 API 구현
  src/main/java/com/heartz/byeboo/adapter/in/web/controller/UserQuestController.java
  src/main/java/com/heartz/byeboo/adapter/out/UserJourneyPersistenceAdapter.java
  src/main/java/com/heartz/byeboo/adapter/out/persistence/repository/UserJourneyRepository.java
  src/main/java/com/heartz/byeboo/application/command/JourneyUpdateCommand.java
  src/main/java/com/heartz/byeboo/application/port/in/UserQuestUseCase.java
  src/main/java/com/heartz/byeboo/application/port/out/RetrieveUserJourneyPort.java
  src/main/java/com/heartz/byeboo/application/service/UserQuestService.java
  src/main/java/com/heartz/byeboo/domain/exception/UserJourneyErrorCode.java
  src/main/java/com/heartz/byeboo/domain/model/User.java
Labels: ✨ Feature, 🐥 현정 🐥

#64 [Deploy] - dev -> main으로 merge
  src/main/java/com/heartz/byeboo/adapter/in/web/controller/HealthCheckController.java
  src/main/java/com/heartz/byeboo/adapter/in/web/controller/QuestController.java
  src/main/java/com/heartz/byeboo/adapter/in/web/controller/UserController.java
  src/main/java/com/heartz/byeboo/adapter/in/web/controller/UserQuestController.java
  src/main/java/com/heartz/byeboo/application/command/SignedUrlCreateCommand.java
  src/main/java/com/heartz/byeboo/application/service/UserService.java
  src/main/java/com/heartz/byeboo/domain/exception/UserQuestErrorCode.java
  src/main/java/com/heartz/byeboo/domain/type/EJourney.java
Labels: 🚀 Deploy

#67 [Refactor] - 전체 퀘스트 조회 API 분리
  src/main/java/com/heartz/byeboo/adapter/in/web/controller/QuestController.java
  src/main/java/com/heartz/byeboo/adapter/in/web/dto/response/quest/AllQuestCompletedResponseDto.java
  src/main/java/com/heartz/byeboo/adapter/in/web/dto/response/quest/AllQuestProgressResponseDto.java
  src/main/java/com/heartz/byeboo/application/command/quest/AllQuestCompletedCommand.java
  src/main/java/com/heartz/byeboo/application/command/quest/AllQuestProgressCommand.java
  src/main/java/com/heartz/byeboo/application/port/in/QuestUseCase.java
  src/main/java/com/heartz/byeboo/application/service/QuestService.java
  src/main/java/com/heartz/byeboo/domain/exception/UserJourneyErrorCode.java
Labels: ♻️ Refactoring, 🦊 상범 🦊

#70 [Refactor] - 유저 생성 API request에 feeling 추가
  src/main/java/com/heartz/byeboo/adapter/in/web/dto/request/UserCreateRequestDto.java
  src/main/java/com/heartz/byeboo/application/command/user/UserCreateCommand.java
Labels: ♻️ Refactoring, 🐥 현정 🐥

#87 [Refactor] - update 로직 변경
  build.gradle
  src/main/java/com/heartz/byeboo/adapter/in/web/dto/request/HomeCountRequestDto.java
  src/main/java/com/heartz/byeboo/adapter/out/UserJourneyPersistenceAdapter.java
  src/main/java/com/heartz/byeboo/adapter/out/UserPersistenceAdapter.java
  src/main/java/com/heartz/byeboo/adapter/out/persistence/entity/UserEntity.java
  src/main/java/com/heartz/byeboo/adapter/out/persistence/entity/UserJourneyEntity.java
  src/main/java/com/heartz/byeboo/config/QueryDslConfig.java
  src/main/java/com/heartz/byeboo/mapper/UserJourneyMapper.java
  src/main/java/com/heartz/byeboo/mapper/UserMapper.java
Labels: ♻️ Refactoring, 🦊 상범 🦊

#88 [Fix] - 진행 중인 여정이 아닌 questNumber에 대한 답변 저장 요청 시 예외 처리
  src/main/java/com/heartz/byeboo/application/service/UserQuestService.java
  src/main/java/com/heartz/byeboo/domain/exception/UserQuestErrorCode.java
Labels: ♻️ Refactoring, 🐥 현정 🐥

#89 [Deploy] - dev -> main으로 merge
  build.gradle
  src/main/java/com/heartz/byeboo/adapter/in/web/dto/request/HomeCountRequestDto.java
  src/main/java/com/heartz/byeboo/adapter/out/UserJourneyPersistenceAdapter.java
  src/main/java/com/heartz/byeboo/adapter/out/UserPersistenceAdapter.java
  src/main/java/com/heartz/byeboo/adapter/out/persistence/entity/UserEntity.java
  src/main/java/com/heartz/byeboo/adapter/out/persistence/entity/UserJourneyEntity.java
  src/main/java/com/heartz/byeboo/application/service/UserQuestService.java
  src/main/java/com/heartz/byeboo/config/QueryDslConfig.java
  src/main/java/com/heartz/byeboo/domain/exception/UserQuestErrorCode.java
  src/main/java/com/heartz/byeboo/mapper/UserJourneyMapper.java
  src/main/java/com/heartz/byeboo/mapper/UserMapper.java
Labels: 🚀 Deploy

#109 [Refactor] - 캐릭터 대사 조회 로직 수정
  src/main/java/com/heartz/byeboo/application/service/UserService.java
Labels: ♻️ Refactoring, 🦊 상범 🦊
