Repository 36-APPJAM-HEARTZ/ByeBoo-SERVER, pull requests merged in 2025-09, with the labels that each got.

#159 [Deploy] - 캐릭터 대사 조회 로직 변경 서버에 반영
  src/main/java/com/heartz/byeboo/application/service/user/UserService.java
Labels: 🦊 상범 🦊, 🚀 Deploy

#161 [Deploy] - 날짜 형식 변환 메서드 추가 서버에 반영
  src/main/java/com/heartz/byeboo/application/service/quest/QuestService.java
  src/main/java/com/heartz/byeboo/utils/TextUtil.java
Labels: 🦊 상범 🦊, 🚀 Deploy

#163 Refactor : 애플 회원 탈퇴에서 authorization_code 헤더로 안받도록 로직 수정
  src/main/java/com/heartz/byeboo/adapter/in/web/controller/OAuthController.java
  src/main/java/com/heartz/byeboo/adapter/out/OAuthUserInfoAdapter.java
  src/main/java/com/heartz/byeboo/adapter/out/persistence/entity/UserEntity.java
  src/main/java/com/heartz/byeboo/application/command/auth/OAuthLoginCommand.java
  src/main/java/com/heartz/byeboo/application/command/auth/OAuthWithdrawCommand.java
  src/main/java/com/heartz/byeboo/application/command/auth/ProviderUserInfoCommand.java
  src/main/java/com/heartz/byeboo/application/command/auth/UserInfoCommand.java
  src/main/java/com/heartz/byeboo/application/port/in/dto/response/auth/UserInfoResponse.java
  src/main/java/com/heartz/byeboo/application/port/out/userinfo/RetrieveUserInfoPort.java
  src/main/java/com/heartz/byeboo/application/port/out/userinfo/UnlinkUserInfoPort.java
  src/main/java/com/heartz/byeboo/application/service/auth/OAuthProvider.java
  src/main/java/com/heartz/byeboo/application/service/auth/OAuthService.java
  src/main/java/com/heartz/byeboo/domain/exception/AuthErrorCode.java
  src/main/java/com/heartz/byeboo/domain/model/User.java
  src/main/java/com/heartz/byeboo/infrastructure/api/apple/AppleOAuthProvider.java
  src/main/java/com/heartz/byeboo/infrastructure/api/kakao/KakaoOAuthProvider.java
  src/main/java/com/heartz/byeboo/infrastructure/dto/SocialInfoResponse.java
  src/main/java/com/heartz/byeboo/mapper/UserMapper.java
Labels: ♻️ Refactoring, 🐥 현정 🐥

#167 [Deploy] : dev -> main으로 merge
  src/main/java/com/heartz/byeboo/adapter/in/web/controller/OAuthController.java
  src/main/java/com/heartz/byeboo/adapter/out/OAuthUserInfoAdapter.java
  src/main/java/com/heartz/byeboo/adapter/out/persistence/entity/UserEntity.java
  src/main/java/com/heartz/byeboo/application/command/auth/OAuthLoginCommand.java
  src/main/java/com/heartz/byeboo/application/command/auth/OAuthWithdrawCommand.java
  src/main/java/com/heartz/byeboo/application/command/auth/ProviderUserInfoCommand.java
  src/main/java/com/heartz/byeboo/application/command/auth/UserInfoCommand.java
  src/main/java/com/heartz/byeboo/application/port/in/dto/response/auth/UserInfoResponse.java
  src/main/java/com/heartz/byeboo/application/port/out/userinfo/RetrieveUserInfoPort.java
  src/main/java/com/heartz/byeboo/application/port/out/userinfo/UnlinkUserInfoPort.java
  src/main/java/com/heartz/byeboo/application/service/auth/OAuthProvider.java
  src/main/java/com/heartz/byeboo/application/service/auth/OAuthService.java
  src/main/java/com/heartz/byeboo/domain/exception/AuthErrorCode.java
  src/main/java/com/heartz/byeboo/domain/model/User.java
  src/main/java/com/heartz/byeboo/infrastructure/api/apple/AppleOAuthProvider.java
  src/main/java/com/heartz/byeboo/infrastructure/api/kakao/KakaoOAuthProvider.java
  src/main/java/com/heartz/byeboo/infrastructure/dto/SocialInfoResponse.java
  src/main/java/com/heartz/byeboo/mapper/UserMapper.java
Labels: 🐥 현정 🐥, 🚀 Deploy
